# Generated by Django 5.0.4 on 2024-08-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='productimage/')),
            ],
        ),
    ]
