# Generated by Django 5.0.4 on 2024-08-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapk', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereg',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profilepic/'),
        ),
    ]
