# Generated by Django 5.1 on 2024-10-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapk', '0003_usereg_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('specialist', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='doctoreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('licenseNumber', models.CharField(max_length=50)),
                ('hospital', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctorimage/')),
            ],
        ),
        migrations.RemoveField(
            model_name='usereg',
            name='profilepic',
        ),
        migrations.AddField(
            model_name='usereg',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usereg',
            name='confirmPassword',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usereg',
            name='contact',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usereg',
            name='firstName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usereg',
            name='lastName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
