# Generated by Django 5.1 on 2024-10-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapk', '0006_doctoreg_confirmpassword_doctoreg_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='drivereg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivername', models.CharField(max_length=100)),
                ('vehicle', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('licenseNumber', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctorimage/')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('confirmPassword', models.CharField(max_length=10)),
            ],
        ),
    ]
