# Generated by Django 4.2.11 on 2024-11-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapk', '0007_cart_drivereg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sellercontact',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sellermail',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sellername',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
