# Generated by Django 5.0.6 on 2024-11-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapk', '0011_usereg_check_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='sellercontact',
            field=models.IntegerField(),
        ),
    ]
