# Generated by Django 5.1.4 on 2024-12-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapk', '0012_alter_cart_sellercontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialist',
            new_name='specialization',
        ),
        migrations.AddField(
            model_name='usereg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
