# Generated by Django 5.1.4 on 2024-12-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapk', '0013_rename_specialist_doctor_specialization_usereg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('diseasedetails', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='drivereg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='driverimage/'),
        ),
    ]
