# Generated by Django 5.1.4 on 2024-12-26 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapk', '0014_appoinment_alter_drivereg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fapk.usereg'),
        ),
    ]
