# Generated by Django 5.1.3 on 2025-01-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapk', '0016_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injuryname', models.CharField(max_length=100)),
                ('procedure', models.CharField(max_length=1000)),
            ],
        ),
    ]
