# Generated by Django 5.1.3 on 2025-01-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapk', '0017_injury'),
    ]

    operations = [
        migrations.AddField(
            model_name='injury',
            name='injuryimg',
            field=models.ImageField(blank=True, null=True, upload_to='injuryimg/'),
        ),
        migrations.AddField(
            model_name='injury',
            name='procedurevideo',
            field=models.FileField(blank=True, null=True, upload_to='injuryprocvideo/'),
        ),
        migrations.AlterField(
            model_name='injury',
            name='procedure',
            field=models.CharField(max_length=100),
        ),
    ]
