# Generated by Django 5.1.3 on 2025-01-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapk', '0018_injury_injuryimg_injury_procedurevideo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivereg',
            name='location',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
