# Generated by Django 5.1.3 on 2025-02-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapk', '0019_drivereg_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacyname', models.CharField(max_length=100)),
                ('ownernam', models.CharField(max_length=100)),
                ('licenseNumber', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('confirmPassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='usereg',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
