# Generated by Django 5.1.3 on 2025-02-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fapk', '0020_pharmacy_alter_usereg_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='ownernam',
            new_name='ownername',
        ),
    ]
