# Generated by Django 5.1.3 on 2025-02-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapk', '0021_rename_ownernam_pharmacy_ownername'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
