# Generated by Django 5.1.4 on 2025-02-16 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapk', '0022_pharmacy_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='totalprice',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='productname',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sellercontact',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sellermail',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sellername',
        ),
        migrations.AddField(
            model_name='cart',
            name='prod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fapk.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fapk.usereg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('order_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fapk.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fapk.usereg')),
            ],
        ),
    ]
