# Generated by Django 5.1.4 on 2025-02-25 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fapk', '0024_rename_prod_cart_products_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
