# Generated by Django 5.1.4 on 2025-02-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapk', '0026_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cart',
        ),
        migrations.AddField(
            model_name='transaction',
            name='cart_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
