# Generated by Django 5.1.4 on 2025-02-27 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fapk', '0027_remove_transaction_cart_transaction_cart_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appoinment',
        ),
    ]
