# Generated by Django 5.1.4 on 2025-02-27 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapk', '0028_delete_appoinment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('diseasedetails', models.CharField(max_length=50)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fapk.doctoreg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fapk.usereg')),
            ],
        ),
    ]
