# Generated by Django 5.1.4 on 2025-02-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapk', '0029_appoinment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
