# Generated by Django 5.1.4 on 2025-02-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapk', '0030_appoinment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injury',
            name='procedure',
            field=models.CharField(max_length=300),
        ),
    ]
