# Generated by Django 5.1.4 on 2025-02-28 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapk', '0031_alter_injury_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivereg',
            name='availability_status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fapk.drivereg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fapk.usereg')),
            ],
        ),
    ]
